# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

markdown: kramdown

# Settings for minima theme

# title: "Yao Xiao's CV"
# author: "Yao Xiao"
# email: yxiaoy@umich.edu
# description: > # this means to ignore newlines until "baseurl:"
# FastClone Github: https://github.com/GuanLab/FastClone_GuanLab
# github_username:  Yaoyx
# linkedin_username: yao-xiao-6a9530192


#Settings for ap theme
title: "Y. X."

author:
  name: Yao Xiao
  desc: CV
  email: yxiaoy@umich.edu
  selfie: profile_photo/profile_pic2.jpeg

social:
  email: true
  github: Yaoyx
  linkedin: https://www.linkedin.com/in/yao-xiao-6a9530192/



  
header_pages:
 - index.md


# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

# theme: minima
remote_theme: kssim/ap

# Google Analytics
google_analytics: G-1SVKELZLEM


